apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: node-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: node-data
      hostPath:
        path: /tmp/webdata
        type: Directory
