apiVersion: v1
kind: Pod
metadata:
  name: production-app
  labels:
    app: prod
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
    - containerPort: 80
    
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 10
      periodSeconds: 5
      
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 5
      failureThreshold: 2
      
    livenessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      failureThreshold: 3
