apiVersion: v1
kind: Pod
metadata:
  name: my-first-lab-pod
  labels:
    app: my-first-lab
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: index-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  volumes:
    - name: index-volume
      configMap:
        name: my-first-lab-index
