apiVersion: v1
kind: Pod
metadata:
  name: log-pod
spec:
  volumes:
    - name: log-vol
      emptyDir: {}

  containers:
    - name: app
      image: busybox
      command:
        - /bin/sh
        - -c
        - while true; do echo "[$(date)] log entry" >> /logs/app.log; sleep 4; done
      volumeMounts:
        - name: log-vol
          mountPath: /logs

    - name: log-reader
      image: busybox
      command:
        - /bin/sh
        - -c
        - tail -f /logs/app.log
      volumeMounts:
        - name: log-vol
          mountPath: /logs
