apiVersion: v1
kind: Pod
metadata:
  name: logger-pod
spec:
  restartPolicy: Always
  containers:
    - name: logger-container
      image: busybox
      command:
        - /bin/sh
        - -c
        - while true; do echo "Hello $(date)"; sleep 5; done
      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
