apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test3
  labels:
    app: nginx
    environment: test
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
